### PR TITLE
Adds support for validating schemas with unsupported formats.

### PR DESCRIPTION
**Pull request by lexicalunit**
According to the JSON Schema specification, validator implementations
are not expected to support custom format attributes that other
implementations may support. Instead of failing to validate schemas
that use custom or unsupported formats, format validation should
simply be skipped in these cases; i.e. validation should succeed.

After looking at a number of different JSON schema validator implementations this seems to be a common way of handling custom formats. For example, the following validator implementations also succeed to validate schemas with unknown/custom/unsupported format types.
- Java: [json-schema-validator](https://github.com/fge/json-schema-validator)
- C++: [libvariant](https://bitbucket.org/gallen/libvariant/)
- Python: [jsonschema](https://github.com/Julian/jsonschema)

### CODE REVIEW

**Comment by vlas-voloshin** [comment]
Thanks for raising this issue and sorry for taking so long to respond! (GitHub doesn't notify on opened pull requests, duh)
You're correct, format keyword validator shouldn't fail when it encounters an unknown format. However, I've decided to take a bit different approach to the problem – it's currently in this branch: https://github.com/vlas-voloshin/JSONSchemaValidation/compare/fix/unknown-formats. Basically, it just removes all "validation" of format name, and the result is the same. Would you mind if I merged my solution instead of the one you proposed?
Additionally, I think it would be a good idea to allow the library clients to register their own format validators, without the need to modify library code at all (which is, as I see, you had to do in your fork). That's something I'll try to work on when I have some free time.

**Comment by lexicalunit** [comment]
Awesome, looks good to me!

**Comment by vlas-voloshin** [comment]
Great, thanks! Looking forward to adding more good stuff to the library.

**Comment by vlas-voloshin** [comment]
@lexicalunit hey just a heads-up: as of version 1.3.0 of the library, it is now possible to define custom format validators to be used with `custom` keyword. Just take a look in `VVJSONSchemaFormatValidator` class header. The UUID format validation you've implemented in a fork can now be implemented simply by registering a validation block for a `uuid` format name before validating schemas. [This test file](https://github.com/vlas-voloshin/JSONSchemaValidation/blob/master/VVJSONSchemaValidationTests/VVJSONSchemaTests.m#L34) actually contains an example of how this could be done.

**Comment by lexicalunit** [comment]
Awesome! I'll definitely check this out when I get a chance. TY for the library and the support :)

**Pull request closed without merging**
